language: java
sudo: true

cache:
  directories:
  - $HOME/.m2
  
jdk:
  - oraclejdk7
 
before_install:
  sudo pip install codecov

script: mvn install

after_success:
  - mvn package jacoco:report coveralls:report

notifications:
  email: false
